import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from 'next/headers' // added
import ContextProvider from '@/context'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "talentapp:project_verification": "d093aca9917964875a0736055996f2a6620288151f0725e6e9e9ae4e450efb50100f5aa6f8d7b6dbaae6b04ea014159e4a278b09b9c489cf2fdce144d14d3eee"
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers()
  const cookies = headersObj.get('cookie')

  return (
    <html lang="en">
      <body
        className={`${inter.style} antialiased`}
      >
        <ContextProvider cookies={cookies}>
          <Navbar />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
